# .github/workflows/main.yml
name: Main Workflow
on:
  push:
    branches: [ main ]

jobs:
  my-template:
    runs-on: ubuntu-latest
    steps:
      - uses: prasadthorati/maven-web-app/.github/workflows/reusable.yaml@main
